name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update WakaTime stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: 'waka'
          PULL_BRANCH_NAME: 'main'
          PUSH_BRANCH_NAME: 'main'
          SHOW_OS: 'true'
          SHOW_PROJECTS: 'true'
          SHOW_EDITORS: 'true'
          SHOW_TIMEZONE: 'false'
          SHOW_COMMIT: 'false'
          SHOW_LANGUAGE: 'true'
          SHOW_LINES_OF_CODE: 'true'
          SHOW_LANGUAGE_PER_REPO: 'false'
          SHOW_LOC_CHART: 'false'
          SHOW_DAYS_OF_WEEK: 'false'
          SHOW_PROFILE_VIEWS: 'false'
          SHOW_SHORT_INFO: 'true'
          SHOW_UPDATED_DATE: 'true'
          SHOW_TOTAL_CODE_TIME: 'true'
          COMMIT_BY_ME: 'true'
          COMMIT_MESSAGE: 'Updated with WakaTime stats'
          COMMIT_USERNAME: 'github-actions[bot]'
          COMMIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
          COMMIT_SINGLE: 'true'
          LOCALE: 'en'
          IGNORED_REPOS: ''
          SYMBOL_VERSION: '1'
          DEBUG_LOGGING: 'true'
